server:
  port: 8090
  
spring:
  application:
    name: load-balancer-servis
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
