server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: recommendation-service
          uri: http://recommendation-service
          predicates:
            - Path=/recommendation-service/**
        - id: flights-service
          uri: http://flights-service
          predicates:
            - Path=/flights-service/**
        - id: users-service
          uri: http://users-service
          predicates:
            - Path=/users-service/**
        - id: reservations-service
          uri: http://reservations-service
          predicates:
            - Path=/reservations-service/**

