server:
  port: 5000

spring:
  application:
    name: flights-service
  neo4j:
    uri: "neo4j+s://6a70dfbe.databases.neo4j.io"
    authentication:
      username: "neo4j"
      password: "9lfusGHyuc3APyUOzIE4IC7KCc16LAS-uuWPg_w93a0"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true