server:
  port: 8080

spring:
  application:
    name: recommendation-service
  neo4j:
    uri: neo4j+s://d0da868e.databases.neo4j.io
    authentication:
      username: neo4j
      password: ipJtHvS4XRAErjTwvALUsVjRW9yNFAWeuh7zhJL0rGE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true